core = 7.x

api = 2

; Include the definition for how to build Drupal core directly, including patches:
; Not needed if you use the default core
includes[] = drupal-org-core.make

; =====================================
; Contrib Modules
; =====================================
; This file was auto-generated by drush make

projects[registry_rebuild][subdir] = "contrib"
projects[registry_rebuild][version] = "2.0"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[answers][subdir] = "contrib"
projects[answers][version] = "3.1"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[best_answer][subdir] = "contrib"
projects[best_answer][version] = "3.0"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[conditional_fields][subdir] = "contrib"
projects[conditional_fields][version] = "3.x-dev"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta7"

projects[custom_search][subdir] = "contrib"
projects[custom_search][version] = "1.13"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[dynamic_cache][subdir] = "contrib"
projects[dynamic_cache][version] = "1.0-rc2"

projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.2"

projects[entitycache][subdir] = "contrib"
projects[entitycache][version] = "1.1"

projects[entityform][subdir] = "contrib"
projects[entityform][version] = "1.2"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-rc3"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta5"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.3"

projects[media][subdir] = "contrib"
projects[media][version] = "1.3"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.7"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta7"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.0-alpha2"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[nodereference_count][subdir] = "contrib"
projects[nodereference_count][version] = "1.0"

projects[nodereference_url][subdir] = "contrib"
projects[nodereference_url][version] = "1.12"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "3.1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[privatemsg][subdir] = "contrib"
projects[privatemsg][version] = "1.4"

projects[pm_existing_pages][subdir] = "contrib"
projects[pm_existing_pages][version] = "1.4"

projects[rate][subdir] = "contrib"
projects[rate][version] = "1.6"

projects[realname][subdir] = "contrib"
projects[realname][version] = "1.1"

projects[role_export][subdir] = "contrib"
projects[role_export][version] = "1.0"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.5"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[taxonomy_edge][subdir] = "contrib"
projects[taxonomy_edge][version] = "1.8"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[token_filter][subdir] = "contrib"
projects[token_filter][version] = "1.1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta6"

projects[views_field_view][subdir] = "contrib"
projects[views_field_view][version] = "1.1"

projects[views_fieldsets][subdir] = "contrib"
projects[views_fieldsets][version] = "1.1"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.11"

projects[weight][subdir] = "contrib"
projects[weight][version] = "2.3"

projects[workbench_access][subdir] = "contrib"
projects[workbench_access][version] = "1.2"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.3"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[ninesixty][subdir] = "contrib"
projects[ninesixty][version] = "1.0"

projects[zen][subdir] = "contrib"
projects[zen][version] = "5.1"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery][download][type] = ""
libraries[jquery][download][url] = ""
libraries[jquery][directory_name] = "jquery"
libraries[jquery][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tcpdf][download][type] = ""
libraries[tcpdf][download][url] = ""
libraries[tcpdf][directory_name] = "tcpdf"
libraries[tcpdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[bootstrap][download][type] = ""
libraries[bootstrap][download][url] = ""
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

