<?php

/**
 * @file
 * Contains mohan.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function mohan_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the mohan module.
    case 'help.page.mohan':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This will get me used to the Drupal 8 way and also dip my feet into angularjs') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function mohan_theme()
{
  $theme = [];

  return $theme;
}
